fail_fast: false
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-vet
      # - id: go-lint
      #- id: go-imports
      #- id: go-cyclo
      #  args: [-over=15]
      #- id: validate-toml
      - id: no-go-testing
      # - id: golangci-lint
      #- id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
        exclude: .devcontainer/
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --indent=4]
        exclude: .devcontainer/
      - id: check-yaml
        exclude: ^pkg/template/testdata/application-templates.*|pkg/bundle/templates/terraform/massdriver.yaml
      - id: end-of-file-fixer
        exclude: ^pkg/template/testdata/application-templates.*
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: no-commit-to-branch
        args: [-b, main]
